# Generated by Django 2.1.2 on 2018-10-13 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0002_auto_20181013_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('plural', models.CharField(blank=True, default='s', max_length=200)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('slayer_level_req', models.PositiveIntegerField(default=0)),
                ('damage', models.PositiveIntegerField(default=0)),
                ('accuracy', models.PositiveIntegerField(default=0)),
                ('armour', models.PositiveIntegerField(default=0)),
                ('is_slayable', models.BooleanField(default=0)),
                ('is_boss', models.BooleanField(default=0)),
                ('is_dragon', models.BooleanField(default=0)),
                ('min_assignable', models.PositiveIntegerField(default=0)),
                ('max_assignable', models.PositiveIntegerField(default=0)),
                ('affinity', models.PositiveIntegerField(choices=[(0, 'Melee'), (0, 'Range'), (0, 'Magic')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(default='Fuck you', max_length=1000)),
                ('level_required', models.PositiveIntegerField(default=0)),
                ('drain', models.PositiveIntegerField(default=0)),
                ('damage', models.PositiveIntegerField(default=0)),
                ('accuracy', models.PositiveIntegerField(default=0)),
                ('armour', models.PositiveIntegerField(default=0)),
                ('chance', models.PositiveIntegerField(default=0)),
                ('factor', models.PositiveIntegerField(default=0)),
                ('gather', models.PositiveIntegerField(default=0)),
                ('keep_factor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, unique=True)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Prayer')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(default='Go something for this person and get some stuff in return.', max_length=40960)),
                ('success', models.CharField(default='You did it!', max_length=4096)),
                ('failure_key', models.CharField(default="You didn't do it!", max_length=4096)),
                ('damage', models.PositiveIntegerField(default=0)),
                ('accuracy', models.PositiveIntegerField(default=0)),
                ('armour', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=0)),
                ('time', models.PositiveIntegerField(default=0)),
                ('has_dragon', models.BooleanField(default=False)),
                ('quest_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Quest')),
            ],
        ),
        migrations.CreateModel(
            name='QuestItemRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Item')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Quest')),
            ],
        ),
        migrations.CreateModel(
            name='QuestItemRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Item')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Quest')),
            ],
        ),
        migrations.AlterField(
            model_name='itemnickname',
            name='nickname',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='quest_req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miniscape.Quest'),
        ),
        migrations.AddField(
            model_name='item',
            name='quest_req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miniscape.Quest'),
        ),
    ]
