# Generated by Django 2.1.2 on 2018-10-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0005_auto_20181013_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(through='miniscape.UserInventory', to='miniscape.Item'),
        ),
    ]
