# Generated by Django 2.1.2 on 2018-10-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0007_auto_20181013_0343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemnickname',
            unique_together={('nickname', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='questitemrequirements',
            unique_together={('quest', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='questitemrewards',
            unique_together={('quest', 'item')},
        ),
    ]
