# Generated by Django 2.1.2 on 2018-10-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0009_user_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
