# Generated by Django 2.1.2 on 2018-10-13 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0010_auto_20181013_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMonsterKills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Monster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='monsters',
            field=models.ManyToManyField(through='miniscape.PlayerMonsterKills', to='miniscape.Monster'),
        ),
        migrations.AlterUniqueTogether(
            name='playermonsterkills',
            unique_together={('user', 'monster')},
        ),
    ]
