# Generated by Django 2.1.2 on 2018-10-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0012_auto_20181013_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='failure_key',
            new_name='failure',
        ),
    ]
