# Generated by Django 2.1.2 on 2018-10-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0013_auto_20181013_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='quest_req',
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_req',
            field=models.ManyToManyField(related_name='_quest_quest_req_+', to='miniscape.Quest'),
        ),
    ]
