# Generated by Django 2.1.2 on 2018-10-14 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0016_user_quests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='quests',
            new_name='completed_quests',
        ),
    ]
