# Generated by Django 2.1.2 on 2018-10-14 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0017_auto_20181014_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterLoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveIntegerField(default=1)),
                ('max_amount', models.PositiveIntegerField(default=1)),
                ('rarity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Item')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Monster')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='monsterloot',
            unique_together={('item', 'monster')},
        ),
    ]
