# Generated by Django 2.1.2 on 2018-10-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0018_auto_20181014_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='loot',
            field=models.ManyToManyField(through='miniscape.MonsterLoot', to='miniscape.Item'),
        ),
    ]
