# Generated by Django 2.1.2 on 2018-10-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0020_auto_20181014_0112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monsterloot',
            unique_together=set(),
        ),
    ]
