# Generated by Django 2.1.2 on 2018-10-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0023_auto_20181014_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ammo_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_ammo', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='back_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_back', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='feet_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_feet', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='hands_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_hands', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='hatchet_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_hatchet', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='head_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_head', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='legs_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_legs', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='mainhand_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_mainhand', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='neck_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_neck', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='offhand_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_offhand', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='pickaxe_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_pickaxe', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='pocket_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_pocket', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='potion_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_potion', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='prayer_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miniscape.Prayer'),
        ),
        migrations.AddField(
            model_name='user',
            name='ring_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_ring', to='miniscape.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='torso_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_torso', to='miniscape.Item'),
        ),
    ]
