# Generated by Django 2.1.2 on 2018-10-14 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0024_auto_20181014_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='active_food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_food', to='miniscape.Item'),
        ),
    ]
