# Generated by Django 2.1.2 on 2018-10-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0025_auto_20181014_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_food',
        ),
        migrations.AddField(
            model_name='item',
            name='food_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
