# Generated by Django 2.1.2 on 2018-10-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0026_auto_20181014_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
