# Generated by Django 2.1.2 on 2018-10-15 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0027_monster_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, unique=True)),
                ('real_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Quest')),
            ],
        ),
        migrations.RenameField(
            model_name='prayernickname',
            old_name='prayer',
            new_name='real_prayer',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='factor',
        ),
        migrations.AddField(
            model_name='prayer',
            name='affinity',
            field=models.PositiveIntegerField(choices=[(0, 'Melee'), (1, 'Range'), (2, 'Magic')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='luck_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='prayer',
            name='nick',
            field=models.ManyToManyField(to='miniscape.PrayerNickname'),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='gather',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='prayernickname',
            unique_together={('nickname', 'real_prayer')},
        ),
        migrations.AddField(
            model_name='quest',
            name='nick',
            field=models.ManyToManyField(to='miniscape.QuestNickname'),
        ),
        migrations.AlterUniqueTogether(
            name='questnickname',
            unique_together={('nickname', 'real_quest')},
        ),
    ]
