# Generated by Django 2.1.2 on 2018-10-15 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0029_monster_quest_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, unique=True)),
                ('real_monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Monster')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='nick',
            field=models.ManyToManyField(to='miniscape.MonsterNickname'),
        ),
        migrations.AlterUniqueTogether(
            name='monsternickname',
            unique_together={('nickname', 'real_monster')},
        ),
    ]
