# Generated by Django 2.1.2 on 2018-10-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0031_auto_20181016_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Quest')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='quests',
        ),
        migrations.AddField(
            model_name='userquest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_quests',
            field=models.ManyToManyField(through='miniscape.UserQuest', to='miniscape.Quest'),
        ),
        migrations.AlterUniqueTogether(
            name='userquest',
            unique_together={('quest', 'user')},
        ),
    ]
