# Generated by Django 2.1.2 on 2018-10-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0033_auto_20181020_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_presets_unlocked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
