# Generated by Django 2.1.2 on 2018-11-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0033_auto_20181124_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisRunes',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniscape.Item')),
            ],
        ),
    ]
