# Generated by Django 2.1.15 on 2022-06-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniscape', '0035_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
