from miniscape.models import Item

ANCIENT_EFFIGY = Item.objects.get(name__iexact='ancient effigy')
CHRISTMAS_CRACKER = Item.objects.get(name__iexact='christmas cracker')
COINS = Item.objects.get(name__iexact='coins')
DIAMOND = Item.objects.get(name__iexact='diamond')
EFFY = Item.objects.get(name__iexact='effy')
EMERALD = Item.objects.get(name__iexact='emerald')
FEDORA = Item.objects.get(name__iexact='fedora')
GEM_ROCK = Item.objects.get(name__iexact='gem rock')
LAPIS_LAZULI = Item.objects.get(name__iexact='lapis lazuli')
OPENED_ANCIENT_EFFIGY = Item.objects.get(name__iexact='opened ancient effigy')
QUARTZ = Item.objects.get(name__iexact='quartz')
REAPER_TOKEN = Item.objects.get(name__iexact='reaper token')
RUBY = Item.objects.get(name__iexact='ruby')
SAPPHIRE = Item.objects.get(name__iexact='sapphire')
SLAYER_HELMET = Item.objects.get(name__iexact='slayer helmet')
VIS_WAX = Item.objects.get(name__iexact='vis wax')
